version: "3.9"

services:
  temporalite:
    image: temporalio/temporalite
    ports:
      - 8233:8233

  worker:
    build:
      context: .
      target: worker-runtime

  client:
    build:
      context: .
      target: client-runtime
    entrypoint: ["sleep", "infinity"]
