version: "3.9"

services:
  temporalite:
    image: temporalio/temporalite
    ports:
      - 8233:8233

  worker:
    build:
      context: .
      target: worker-runtime
    depends_on:
      - temporalite

  client:
    build:
      context: .
      target: client-runtime
    depends_on:
      - temporalite
