version: "3.9"

services:
  temporalite:
    build: https://github.com/temporalio/temporalite.git#main
    ports:
      - 7233:7233
      - 8233:8233

  worker:
    build:
      context: .
      target: runtime
